# Generated by Django 4.2.1 on 2023-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('killer', models.CharField(choices=[('Evan MacMillan', 'The Trapper'), ('Max Thompson Jr', 'The Hillbilly'), ('Lisa Sherwood', 'The Hag'), ('Anna', 'Huntress'), ('Micheal Myers', 'The Shape'), ('Adiris', 'The Plague'), ('Rin Yamaoka', 'The spirit'), ('Kazan Yamaoka', 'The Oni'), ('Frank', 'The Legion'), ('Carmina Mora', 'The Artist'), ('Danny Johnson', 'ghost face'), ('Bubba Sawyer', 'The Cannibal'), ('Amanda Sawyer', 'The pig'), ('Herman Carter', 'The Doctor'), ('Sally Smithson', 'The Nurse'), ('Nemesis', 'Nemesis'), ('Demogorgon', 'Demodogo'), ('Ji-woon Hak', 'The Trickster'), ('Talbot Grimes', 'The Blight'), ('Elliot Spencer / pinhead', 'The Cenobite'), ('Freddy Krueger', 'Nightmare'), ('Jeffrey Hawk', 'The Clown'), ('Phillip Ojomo', 'The Wraith'), ('Victor & Charlotte', 'The Twins'), ('Pyramid head', 'Executioner'), ('Caleb Quin', 'DeathSlinger'), ('Tarhos Kovacs', 'The knight'), ('Adrianaimai', 'The skull merchant'), ('Dredge', 'Dredge'), ('Albert Wesker', 'Mastermind'), ('Sadoko Yamamura', 'The Onryo')], default='The Trapper', max_length=24)),
                ('Game_map', models.CharField(choices=[('Raccoon City', 'Raccoon City'), ('Silent Hill', 'Midwitch elementary school'), ('Garden of Joy', 'Garden of joy')], default='Raccoon City', max_length=24)),
                ('deaths', models.IntegerField(default=4)),
                ('Gens_completed', models.IntegerField(default=0)),
                ('Faul_play', models.CharField(choices=[('face camping', 'face camping'), ('Tunneling', 'Tunneling'), ('NA', 'NA'), ('camping', 'camping')], default='NA', max_length=20)),
                ('overal_fun', models.IntegerField(default=5)),
            ],
        ),
    ]
