# Generated by Django 4.2.1 on 2023-05-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbd_stats', '0002_game_mori_game_sweat_alter_game_gens_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Insta_down',
            field=models.BooleanField(default=False),
        ),
    ]
