# Generated by Django 4.2.1 on 2023-05-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbd_stats', '0003_game_insta_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.CharField(choices=[('FUN', 'FUN'), ('Irritated', 'rritated'), ('tired', 'tired'), ('meh', 'meh')], default='FUN', max_length=9),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.CharField(choices=[('FUN', 'FUN'), ('Irritated', 'rritated'), ('tired', 'tired'), ('meh', 'meh')], default='FUN', max_length=9),
        ),
        migrations.AddField(
            model_name='game',
            name='player_3',
            field=models.CharField(choices=[('FUN', 'FUN'), ('Irritated', 'rritated'), ('tired', 'tired'), ('meh', 'meh')], default='FUN', max_length=9),
        ),
        migrations.AddField(
            model_name='game',
            name='player_4',
            field=models.CharField(choices=[('FUN', 'FUN'), ('Irritated', 'rritated'), ('tired', 'tired'), ('meh', 'meh')], default='FUN', max_length=9),
        ),
    ]
